pipeline {
    agent any
    environment {
        REPO_DIR = "${env.WORKSPACE}"
        BUILD_DIR = "${REPO_DIR}/dist"
    }
    stages {
        stage('Install Dependencies') {
            steps {
                dir(REPO_DIR) {
                    sh 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir(REPO_DIR) {
                    sh 'npm run build'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh "sudo mkdir -p /opt/proyectos/dist"
                    sh "sudo cp -r ${BUILD_DIR}/* /opt/proyectos/dist/"
                    sh 'sudo systemctl restart nginx'
                }
            }
        }
    }
}
