pipeline {
    agent any
    environment {
        REPO_DIR = '/opt/proyectos'
        BUILD_DIR = "${REPO_DIR}/dist"
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    if (!fileExists(REPO_DIR)) {
                        sh "mkdir -p ${REPO_DIR}"
                        dir(REPO_DIR) {
                            git url: 'https://github.com/CoilBetrox/portafolio-rdtr.git'
                        }
                    } else {
                        dir(REPO_DIR) {
                            sh 'git pull'
                        }
                    }
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                dir(REPO_DIR) {
                    sh 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir(REPO_DIR) {
                    sh 'npm run build'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh "sudo cp -r ${BUILD_DIR}/* /opt/proyectos/dist/"
                    sh 'sudo systemctl restart nginx'
                }
            }
        }
    }
}
